console.log("avanzar uno");
console.log("si hay montaña quitar");
console.log("si hay agujero tapar");
console.log("avanzar uno");
console.log("si hay montaña quitar");
console.log("si hay agujero tapar");
console.log("avanzar uno");
console.log("si hay montaña quitar");
console.log("si hay agujero tapar");
console.log("avanzar uno");
console.log("si hay montaña quitar");
console.log("si hay agujero tapar");
console.log("avanzar uno");
console.log("si hay montaña quitar");
console.log("si hay agujero tapar");
console.log("avanzar uno");
console.log("si hay montaña quitar");
console.log("si hay agujero tapar");
console.log("avanzar uno");
console.log("si hay montaña quitar");
console.log("si hay agujero tapar");
